version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "eslint"
      - dependency-name: "eslint-config-prettier"
      - dependency-name: "eslint-plugin-react"
      - dependency-name: "eslint-plugin-vue"
      - dependency-name: "@typescript-eslint/eslint-plugin"
